# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  pull_request:
    branches: [ testing, main ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: 'Install Node'
      uses: actions/setup-node@v1
    - name: npm install, build, and test
      run: |
        rm -rf node_modules
        npm install
        npm run build --if-present
        npm run test --if-present
